# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    container_name: app
    build: .
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mobbaas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Database Service (Psql)
  db:
    image: 'postgres:13-alpine'
    container_name: db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mobbaas
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

# Volumes
volumes:
  postgres-data:

# Networks to be created to facilitate communication between containers
networks:
  backend: